/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("org.neo4j.driver:neo4j-java-driver:6.0.4")
}

application {
    // Define the main class for the application.
    mainClass = "org.frauddetection.App"
}
